const router = require("express").Router()
const auth = require("../middleware/authMiddleware")
const profile = require("../controllers/profileController")
router.use(auth)
router.get("/", profile.getProfile)
router.put("/", profile.updateProfile)
router.put("/settings", profile.updateSettings)
router.put("/theme", profile.updateTheme)
router.put("/password", profile.changePassword)
router.post("/avatar", profile.updateAvatar)
router.delete("/avatar", profile.removeAvatar)
router.get("/export", profile.exportData)
router.delete("/account", profile.deleteAccount)
module.exports = router
